# Generated by Django 4.2.3 on 2023-07-19 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('privacy_level', models.CharField(choices=[('public', 'Все'), ('link_only', 'Люди по ссылке'), ('private', 'Только я')], default='public', max_length=9)),
                ('tags', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('file', 'Файл'), ('group', 'Группа')], max_length=9)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='file',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AlterField(
            model_name='file',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.group'),
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.resource'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.category'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.resource'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.resource'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='resource',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='API.resource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='resource',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='API.resource'),
            preserve_default=False,
        ),
    ]
