# Generated by Django 4.2.3 on 2023-07-23 19:26

import API.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_favorite_resource_resourcecategory_resourcegroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='', upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('file', 'Файл'), ('group', 'Группа')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True, validators=[API.validators.UsernameValidator]),
        ),
    ]
