# Generated by Django 4.2.3 on 2023-07-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_file_file_path_file_file_alter_resource_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='API.resource'),
        ),
        migrations.AlterField(
            model_name='group',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='API.resource'),
        ),
    ]
