# Generated by Django 4.2.3 on 2023-07-26 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_file_resource_alter_group_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='API.resource'),
        ),
    ]
