# Generated by Django 4.2.3 on 2023-07-29 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_group_resources_resource_slug_alter_group_resource_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.AddField(
            model_name='resource',
            name='favorites',
            field=models.ManyToManyField(db_table='API_favorite', to=settings.AUTH_USER_MODEL),
        ),

    ]
