# Generated by Django 4.2.3 on 2023-08-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_resource_favorites_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resourcecategory',
            name='resource',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ResourceCategory',
        ),
    ]
