# Generated by Django 4.2.3 on 2023-08-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_remove_resourcecategory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at']},
        ),
    ]
